//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Ban_Dien_Thoai.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sell_Mobile_1Entities : DbContext
    {
        public Sell_Mobile_1Entities()
            : base("name=Sell_Mobile_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<tb_CTDonHang> tb_CTDonHang { get; set; }
        public DbSet<tb_DienThoai> tb_DienThoai { get; set; }
        public DbSet<tb_DonHang> tb_DonHang { get; set; }
        public DbSet<tb_KhachHang> tb_KhachHang { get; set; }
        public DbSet<tb_LoaiSanPham> tb_LoaiSanPham { get; set; }
        public DbSet<tb_NhaSanXuat> tb_NhaSanXuat { get; set; }
    }
}
