//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Ban_Dien_Thoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CTDonHang
    {
        public int MaDH { get; set; }
        public int MaDienThoai { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DonGia { get; set; }
    
        public virtual tb_DienThoai tb_DienThoai { get; set; }
        public virtual tb_DonHang tb_DonHang { get; set; }
    }
}
