//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Ban_Dien_Thoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DienThoai
    {
        public tb_DienThoai()
        {
            this.tb_CTDonHang = new HashSet<tb_CTDonHang>();
        }
    
        public int MaDienThoai { get; set; }
        public string TenDienThoai { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string Mota { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string HinhSP1 { get; set; }
        public string HinhSP2 { get; set; }
        public string HinhSP3 { get; set; }
        public string HinhSP4 { get; set; }
        public string KichThuocHinhAnh { get; set; }
        public string Camera_Truoc { get; set; }
        public string Camera_Sau { get; set; }
        public string He_Dieu_Hanh { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string Bo_Nho_Trong { get; set; }
        public string The_Nho { get; set; }
        public string Sim { get; set; }
        public string Ket_Noi { get; set; }
        public string Pin { get; set; }
        public string ChuThich { get; set; }
        public Nullable<int> MaNSX { get; set; }
    
        public virtual ICollection<tb_CTDonHang> tb_CTDonHang { get; set; }
        public virtual tb_LoaiSanPham tb_LoaiSanPham { get; set; }
        public virtual tb_NhaSanXuat tb_NhaSanXuat { get; set; }
    }
}
