//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Ban_Dien_Thoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_KhachHang
    {
        public tb_KhachHang()
        {
            this.tb_DonHang = new HashSet<tb_DonHang>();
        }
    
        public int MaKH { get; set; }
        public string HoTen { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string Diachi { get; set; }
        public string DienThoai { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        public virtual ICollection<tb_DonHang> tb_DonHang { get; set; }
    }
}
